# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-w" -v -o ./bin/zellij-store ./cmd/cli/main.go
  install:
    deps:
      - build
    cmds:
      - cp ./bin/zellij-store ~/.local/bin/
